name: Sorbet
on:
  pull_request:
  push:
    branches: ["main"]
jobs:
  sorbet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ruby & run 'bundle install' and caches gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Sorbet
        run: bundle exec srb tc
